2024-10-24T13:22:01.253949346Z W1024 13:22:01.253775       1 deprecated.go:66] 
2024-10-24T13:22:01.253949346Z ==== Removed Flag Warning ======================
2024-10-24T13:22:01.253949346Z 
2024-10-24T13:22:01.253949346Z logtostderr is removed in the k8s upstream and has no effect any more.
2024-10-24T13:22:01.253949346Z 
2024-10-24T13:22:01.253949346Z ===============================================
2024-10-24T13:22:01.253949346Z 		
2024-10-24T13:22:01.254749248Z I1024 13:22:01.254693       1 kube-rbac-proxy.go:233] Valid token audiences: 
2024-10-24T13:22:01.257027916Z I1024 13:22:01.256944       1 kube-rbac-proxy.go:347] Reading certificate files
2024-10-24T13:22:01.257724727Z I1024 13:22:01.257691       1 kube-rbac-proxy.go:395] Starting TCP socket on :9154
2024-10-24T13:22:01.258150733Z I1024 13:22:01.258126       1 kube-rbac-proxy.go:402] Listening securely on :9154
2024-10-24T13:31:17.860951930Z E1024 13:31:17.860830       1 webhook.go:154] Failed to make webhook authenticator request: Post "https://172.30.0.1:443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 172.30.0.1:443: connect: connection refused
2024-10-24T13:31:17.860951930Z E1024 13:31:17.860892       1 auth.go:47] Unable to authenticate the request due to an error: Post "https://172.30.0.1:443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 172.30.0.1:443: connect: connection refused
2024-10-24T13:31:47.855784995Z E1024 13:31:47.855719       1 webhook.go:154] Failed to make webhook authenticator request: Post "https://172.30.0.1:443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 172.30.0.1:443: connect: connection refused
2024-10-24T13:31:47.855868950Z E1024 13:31:47.855782       1 auth.go:47] Unable to authenticate the request due to an error: Post "https://172.30.0.1:443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 172.30.0.1:443: connect: connection refused
2024-10-24T13:32:02.738080363Z E1024 13:32:02.738017       1 webhook.go:154] Failed to make webhook authenticator request: Post "https://172.30.0.1:443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 172.30.0.1:443: connect: connection refused
2024-10-24T13:32:02.738080363Z E1024 13:32:02.738064       1 auth.go:47] Unable to authenticate the request due to an error: Post "https://172.30.0.1:443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 172.30.0.1:443: connect: connection refused
2024-10-24T13:32:17.855691321Z E1024 13:32:17.855588       1 webhook.go:154] Failed to make webhook authenticator request: Post "https://172.30.0.1:443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 172.30.0.1:443: connect: connection refused
2024-10-24T13:32:17.855691321Z E1024 13:32:17.855643       1 auth.go:47] Unable to authenticate the request due to an error: Post "https://172.30.0.1:443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 172.30.0.1:443: connect: connection refused
2024-10-24T13:32:32.733521625Z E1024 13:32:32.733451       1 webhook.go:154] Failed to make webhook authenticator request: Post "https://172.30.0.1:443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 172.30.0.1:443: connect: connection refused
2024-10-24T13:32:32.733521625Z E1024 13:32:32.733508       1 auth.go:47] Unable to authenticate the request due to an error: Post "https://172.30.0.1:443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 172.30.0.1:443: connect: connection refused
2024-10-24T13:32:47.856609282Z E1024 13:32:47.856545       1 webhook.go:154] Failed to make webhook authenticator request: Post "https://172.30.0.1:443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 172.30.0.1:443: connect: connection refused
2024-10-24T13:32:47.856681110Z E1024 13:32:47.856606       1 auth.go:47] Unable to authenticate the request due to an error: Post "https://172.30.0.1:443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 172.30.0.1:443: connect: connection refused
2024-10-24T13:33:02.733171005Z E1024 13:33:02.733106       1 webhook.go:154] Failed to make webhook authenticator request: Post "https://172.30.0.1:443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 172.30.0.1:443: connect: connection refused
2024-10-24T13:33:02.733171005Z E1024 13:33:02.733158       1 auth.go:47] Unable to authenticate the request due to an error: Post "https://172.30.0.1:443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 172.30.0.1:443: connect: connection refused
