2024-10-24T13:02:49.284426605Z + [[ -f /env/_master ]]
2024-10-24T13:02:49.284617925Z + ho_enable=--enable-hybrid-overlay
2024-10-24T13:02:49.285040315Z ++ date '+%m%d %H:%M:%S.%N'
2024-10-24T13:02:49.287807284Z + echo 'I1024 13:02:49.287315605 - network-node-identity - start webhook'
2024-10-24T13:02:49.287901075Z I1024 13:02:49.287315605 - network-node-identity - start webhook
2024-10-24T13:02:49.287973815Z + exec /usr/bin/ovnkube-identity --k8s-apiserver=https://api-int.ci-op-2fcpj5j6-f6035.XXXXXXXXXXXXXXXXXXXXXX:6443 --webhook-cert-dir=/etc/webhook-cert --webhook-host=127.0.0.1 --webhook-port=9743 --enable-hybrid-overlay --enable-interconnect --disable-approver --extra-allowed-user=system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-control-plane --wait-for-kubernetes-api=200s --pod-admission-conditions=/var/run/ovnkube-identity-config/additional-pod-admission-cond.json --loglevel=2
2024-10-24T13:02:49.323305283Z I1024 13:02:49.320735       1 ovnkubeidentity.go:132] Config: {kubeconfig: apiServer:https://api-int.ci-op-2fcpj5j6-f6035.XXXXXXXXXXXXXXXXXXXXXX:6443 logLevel:2 port:9743 host:127.0.0.1 certDir:/etc/webhook-cert metricsAddress:0 leaseNamespace: enableInterconnect:true enableHybridOverlay:true disableWebhook:false disableApprover:true waitForKAPIDuration:200000000000 localKAPIPort:6443 extraAllowedUsers:{slice:[system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-control-plane] hasBeenSet:true} csrAcceptanceConditionFile: csrAcceptanceConditions:[] podAdmissionConditionFile:/var/run/ovnkube-identity-config/additional-pod-admission-cond.json podAdmissionConditions:[]}
2024-10-24T13:02:49.323305283Z W1024 13:02:49.320859       1 client_config.go:659] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2024-10-24T13:02:49.323305283Z I1024 13:02:49.321858       1 ovnkubeidentity.go:351] Waiting for caches to sync
2024-10-24T13:02:49.343638301Z I1024 13:02:49.343560       1 reflector.go:359] Caches populated for *v1.Node from k8s.io/client-go/informers/factory.go:160
2024-10-24T13:02:49.423047527Z I1024 13:02:49.422996       1 certwatcher.go:161] "Updated current TLS certificate" logger="controller-runtime.certwatcher"
2024-10-24T13:02:49.423368638Z I1024 13:02:49.423305       1 certwatcher.go:115] "Starting certificate watcher" logger="controller-runtime.certwatcher"
2024-10-24T13:02:49.423441947Z I1024 13:02:49.423419       1 ovnkubeidentity.go:430] Starting the webhook server
2024-10-24T13:08:37.422860051Z W1024 13:08:37.422633       1 reflector.go:470] k8s.io/client-go/informers/factory.go:160: watch of *v1.Node ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
2024-10-24T13:08:54.125065472Z W1024 13:08:54.124062       1 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Node: Get "https://api-int.ci-op-2fcpj5j6-f6035.XXXXXXXXXXXXXXXXXXXXXX:6443/api/v1/nodes?resourceVersion=14586": dial tcp 10.0.0.2:6443: connect: connection refused
2024-10-24T13:08:54.125233562Z I1024 13:08:54.125167       1 trace.go:236] Trace[1093597223]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:160 (24-Oct-2024 13:08:38.619) (total time: 15505ms):
2024-10-24T13:08:54.125233562Z Trace[1093597223]: ---"Objects listed" error:Get "https://api-int.ci-op-2fcpj5j6-f6035.XXXXXXXXXXXXXXXXXXXXXX:6443/api/v1/nodes?resourceVersion=14586": dial tcp 10.0.0.2:6443: connect: connection refused 15504ms (13:08:54.124)
2024-10-24T13:08:54.125233562Z Trace[1093597223]: [15.505339376s] [15.505339376s] END
2024-10-24T13:08:54.125296602Z E1024 13:08:54.125240       1 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://api-int.ci-op-2fcpj5j6-f6035.XXXXXXXXXXXXXXXXXXXXXX:6443/api/v1/nodes?resourceVersion=14586": dial tcp 10.0.0.2:6443: connect: connection refused
2024-10-24T13:08:57.326519615Z W1024 13:08:57.326396       1 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Node: Get "https://api-int.ci-op-2fcpj5j6-f6035.XXXXXXXXXXXXXXXXXXXXXX:6443/api/v1/nodes?resourceVersion=14586": dial tcp 10.0.0.2:6443: connect: connection refused
2024-10-24T13:08:57.326519615Z E1024 13:08:57.326508       1 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://api-int.ci-op-2fcpj5j6-f6035.XXXXXXXXXXXXXXXXXXXXXX:6443/api/v1/nodes?resourceVersion=14586": dial tcp 10.0.0.2:6443: connect: connection refused
2024-10-24T13:09:31.124619609Z W1024 13:09:31.124522       1 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Node: Get "https://api-int.ci-op-2fcpj5j6-f6035.XXXXXXXXXXXXXXXXXXXXXX:6443/api/v1/nodes?resourceVersion=14586": dial tcp 10.0.0.2:6443: i/o timeout
2024-10-24T13:09:31.124619609Z I1024 13:09:31.124609       1 trace.go:236] Trace[1386923755]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:160 (24-Oct-2024 13:09:01.100) (total time: 30024ms):
2024-10-24T13:09:31.124619609Z Trace[1386923755]: ---"Objects listed" error:Get "https://api-int.ci-op-2fcpj5j6-f6035.XXXXXXXXXXXXXXXXXXXXXX:6443/api/v1/nodes?resourceVersion=14586": dial tcp 10.0.0.2:6443: i/o timeout 30024ms (13:09:31.124)
2024-10-24T13:09:31.124619609Z Trace[1386923755]: [30.024143103s] [30.024143103s] END
2024-10-24T13:09:31.124703839Z E1024 13:09:31.124630       1 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://api-int.ci-op-2fcpj5j6-f6035.XXXXXXXXXXXXXXXXXXXXXX:6443/api/v1/nodes?resourceVersion=14586": dial tcp 10.0.0.2:6443: i/o timeout
2024-10-24T13:09:38.160841935Z W1024 13:09:38.160768       1 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Node: Get "https://api-int.ci-op-2fcpj5j6-f6035.XXXXXXXXXXXXXXXXXXXXXX:6443/api/v1/nodes?resourceVersion=14586": dial tcp 10.0.0.2:6443: connect: connection refused
2024-10-24T13:09:38.160841935Z E1024 13:09:38.160824       1 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://api-int.ci-op-2fcpj5j6-f6035.XXXXXXXXXXXXXXXXXXXXXX:6443/api/v1/nodes?resourceVersion=14586": dial tcp 10.0.0.2:6443: connect: connection refused
2024-10-24T13:09:55.783912143Z W1024 13:09:55.783769       1 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Node: Get "https://api-int.ci-op-2fcpj5j6-f6035.XXXXXXXXXXXXXXXXXXXXXX:6443/api/v1/nodes?resourceVersion=14586": dial tcp 10.0.0.2:6443: connect: connection refused
2024-10-24T13:09:55.783912143Z E1024 13:09:55.783845       1 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://api-int.ci-op-2fcpj5j6-f6035.XXXXXXXXXXXXXXXXXXXXXX:6443/api/v1/nodes?resourceVersion=14586": dial tcp 10.0.0.2:6443: connect: connection refused
2024-10-24T13:10:44.960764918Z I1024 13:10:44.960686       1 reflector.go:359] Caches populated for *v1.Node from k8s.io/client-go/informers/factory.go:160
2024-10-24T13:13:37.184568641Z I1024 13:13:37.184440       1 reflector.go:359] Caches populated for *v1.Node from k8s.io/client-go/informers/factory.go:160
2024-10-24T13:15:19.993690102Z I1024 13:15:19.993603       1 reflector.go:359] Caches populated for *v1.Node from k8s.io/client-go/informers/factory.go:160
2024-10-24T13:19:03.787179574Z I1024 13:19:03.787114       1 reflector.go:359] Caches populated for *v1.Node from k8s.io/client-go/informers/factory.go:160
2024-10-24T13:25:09.619317447Z I1024 13:25:09.619152       1 reflector.go:359] Caches populated for *v1.Node from k8s.io/client-go/informers/factory.go:160
2024-10-24T13:29:37.685551860Z I1024 13:29:37.685468       1 reflector.go:359] Caches populated for *v1.Node from k8s.io/client-go/informers/factory.go:160
2024-10-24T13:33:08.147003191Z I1024 13:33:08.146914       1 reflector.go:359] Caches populated for *v1.Node from k8s.io/client-go/informers/factory.go:160
2024-10-24T14:07:56.105308902Z 2024/10/24 14:07:56 http: TLS handshake error from 127.0.0.1:60882: EOF
